services:
  db:
    image: postgres:15-alpine
    container_name: saas_clinico_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: saas_clinica_db
    volumes:
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: saas_clinico_adminer
    restart: always
    ports:
      - "8080:8080"
